version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase  
      - GRPC_PORT=4200
    depends_on:
      - db