env: "local"

database:
  host: "postgres"
  port: 5432
  username: "rmarsu"
  password: "qwerty"

grpc:
  port: 8080
  max_connection_idle: 5s
  timeout: 15s
  max_connection_age: 5s

jwt:
  salt : "my_salt"
  ttl : 3600s

hasher:
  salt : "my_salt"
